apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "medusa.fullname" . }}-postgres
  labels:
    {{- include "medusa.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
