apiVersion: v1
kind: Service
metadata:
  name: {{ include "medusa.fullname" . }}-postgres
  labels:
    {{- include "medusa.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/component: postgres
    {{- include "medusa.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "medusa.fullname" . }}-redis
  labels:
    {{- include "medusa.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/component: redis
    {{- include "medusa.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "medusa.fullname" . }}-backend
  labels:
    {{- include "medusa.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: backend
    {{- include "medusa.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "medusa.fullname" . }}-storefront
  labels:
    {{- include "medusa.labels" . | nindent 4 }}
    app.kubernetes.io/component: storefront
spec:
  type: {{ .Values.service.storefront.type }}
  ports:
    - port: {{ .Values.service.storefront.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: storefront
    {{- include "medusa.selectorLabels" . | nindent 4 }}
