apiVersion: v1
kind: Service
metadata:
  name: {{ include "woocommerce.fullname" . }}-wordpress
  labels:
    {{- include "woocommerce.labels" . | nindent 4 }}
spec:
  type: {{ .Values.wordpress.serviceType }}
  ports:
    - port: {{ .Values.wordpress.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: wordpress
    {{- include "woocommerce.selectorLabels" . | nindent 4 }}
